// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzehhjngwliubtllpoek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6ZWhoam5nd2xpdWJ0bGxwb2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjMyMjgsImV4cCI6MjA2OTA5OTIyOH0.hxF3aUH2tJS_PRweJ2OIU47yKI3msBnEyQ8EoklOjo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});